# Generated by Django 5.1.1 on 2024-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzerapp', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='blanks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
